export const url_servers = {
    key_server: 'tueba',
    realm: 'lcms',
    port: '10091',
    port_socket: '10092',
    host: ['http://localhost'],
    ws_url: ['wss://', 'localhost'],
    pageTitle: '[LCMS] - Hệ thống quản lý học tập trực tuyến, Trường Đại học Kinh tế và Quản trị kinh doanh',
    X_APP_ID: '7AA76A7E-5BDE-40AE-A0FE-F85CFA0C2BE2',//'0645451e-3396-41eb-8d02-ae39cb030cdd', //'7AA76A7E-5BDE-40AE-A0FE-F85CFA0C2BE2',
    localhost: '0645451e-3396-41eb-8d02-ae39cb030cdd',
    google_client_id: '370352596447-qoehacvhc49lpf6hp2nsllqqkbd078ri.apps.googleusercontent.com',
    ketServer_api: `https://apps.ictu.vn:9081/tracnghiem_ket/api/v1/`,
    thikhacServer_api: `https://apps.ictu.vn:9081/thikhac/api/v1/`,
    driveFolders_id: '1LT5vL0AAVy3NxLGkNB7-OAX4cSiNcjSA',
    lectureData_id: '1pZnWJlW4C3WQsKq4B90gmCL8ORsCf3yj',
    studentData_id: '1ziFcZenGCf_qQDHkjwA7aLyPBde0od0N',
    driveImage_id: '1KaWFZTpECwlanpYovIapqWFIinsnTUVw',
    driveVideo_id: '1qzXI3D0OEnelcgOjbEtHQYJ6KTv0EM92',
    video_marker: false,
    donviquanly: 'Đại Học Thái Nguyên',
    donvitructhuoc: 'Trường Đại Học Kinh tế và Quản trị kinh doanh',
    class_main: '',
    file_server: 'serverAws',
    title: 'DTKH-ICTU',
    domain: 'dtkh.ictu.edu.vn',
    codeByLvl: false,
    unlimitLesson: false,
    newTestThuchanh: false,
    dragDropLesson: false,
    isDttx: false,
    loadNewCom: false,
    no_test_question: false,
}