export const url_servers = {
    key_server: 'hvu',
    realm: 'hvu',
    port: '10083',
    port_socket: '10084',
    host: ['https://apiv3.ictu.edu.vn'],
    ws_url: ['wss://', 'apiv3.ictu.edu.vn'],
    pageTitle: 'HVU-iBLS',
    X_APP_ID: 'E59AB038-9912-4580-9998-320C9719C6E5',
    localhost: '0645451e-3396-41eb-8d02-ae39cb030cdd',
    google_client_id: '196027039836-kjhoo8f8p3i2eldcodouvs94p1gbi4jo.apps.googleusercontent.com',
    ketServer_api: `https://apps.ictu.vn:9081/tracnghiem_ket/api/v1/`,
    thikhacServer_api: `https://apps.ictu.vn:9081/thikhac/api/v1/`,
    driveFolders_id: '1LT5vL0AAVy3NxLGkNB7-OAX4cSiNcjSA',
    lectureData_id: '1pZnWJlW4C3WQsKq4B90gmCL8ORsCf3yj',
    studentData_id: '1ziFcZenGCf_qQDHkjwA7aLyPBde0od0N',
    driveImage_id: '1KaWFZTpECwlanpYovIapqWFIinsnTUVw',
    driveVideo_id: '1qzXI3D0OEnelcgOjbEtHQYJ6KTv0EM92',
    video_marker: true,
    donviquanly: '',
    donvitructhuoc: 'TRƯỜNG ĐẠI HỌC HÙNG VƯƠNG',
    class_main: '',
    file_server: 'serverAws',
    title: 'HVU-iBLS',
    domain: 'giangvien.hvu.edu.vn',
    codeByLvl: true,
    unlimitLesson: true,
    appVersion: '3.0.58',
    newTestThuchanh: true,
    dragDropLesson: false,
    isDttx: false,
    loadNewCom: true,
    no_test_question: true,
}
