export const url_servers = {
    key_server: 'tueba_dttx',
    realm: 'tuebadttx',
    port: '8081',
    port_socket: '8082',
    host: ['https://giangvientuxa.tueba.edu.vn'],
    ws_url: ['wss://', 'giangvientuxa.tueba.edu.vn'],
    pageTitle: '[DTTX] - Trường Đại học Kinh tế và Quản trị kinh doanh',
    X_APP_ID: 'D4311175-BBE6-4B2B-B359-DD5C1C0C9C5F',//'0645451e-3396-41eb-8d02-ae39cb030cdd', //'7AA76A7E-5BDE-40AE-A0FE-F85CFA0C2BE2',
    localhost: '3BD113C8-DC14-4854-A64B-FBAFEF51BAAB',
    google_client_id: '370352596447-qoehacvhc49lpf6hp2nsllqqkbd078ri.apps.googleusercontent.com',
    ketServer_api: `https://apps.ictu.vn:9081/tracnghiem_ket/api/v1/`,
    thikhacServer_api: `https://apps.ictu.vn:9081/thikhac/api/v1/`,
    driveFolders_id: '1LT5vL0AAVy3NxLGkNB7-OAX4cSiNcjSA',
    lectureData_id: '1pZnWJlW4C3WQsKq4B90gmCL8ORsCf3yj',
    studentData_id: '1ziFcZenGCf_qQDHkjwA7aLyPBde0od0N',
    driveImage_id: '1KaWFZTpECwlanpYovIapqWFIinsnTUVw',
    driveVideo_id: '1qzXI3D0OEnelcgOjbEtHQYJ6KTv0EM92',
    video_marker: true,
    donviquanly: 'Đại Học Thái Nguyên',
    donvitructhuoc: 'Trường Đại Học Kinh tế và Quản trị kinh doanh',
    class_main: '',
    file_server: 'serverAws',
    title: 'DTTX-TUEBA',
    domain: 'giangvientuxa.tueba.edu.vn',
    codeByLvl: true,
    unlimitLesson: true,
    appVersion: '3.0.43',
    newTestThuchanh: true,
    dragDropLesson: true,
    isDttx: true,
    loadNewCom: true,
    no_test_question: true,
}