export const url_servers = {
    key_server: 'ictu',
    realm: 'ionline',
    port: '9087',
    port_socket: '9088',
    host: ['https://apps.ictu.edu.vn'],
    ws_url: ['wss://', 'apps.ictu.edu.vn'],
    pageTitle: '[DTKH] - Hệ thống quản lý học tập trực tuyến, Trường Đại học CNTT & TT',
    X_APP_ID: '92F11D59-90FB-4652-A2F4-D44CDED70E35',
    localhost: '0645451e-3396-41eb-8d02-ae39cb030cdd',
    google_client_id: '973389896263-11sa03rtspsn2fap5uo160l3opa7n62t.apps.googleusercontent.com',
    ketServer_api: `https://apps.ictu.vn:9081/tracnghiem_ket/api/v1/`,
    thikhacServer_api: `https://apps.ictu.vn:9081/thikhac/api/v1/`,
    driveFolders_id: '1LT5vL0AAVy3NxLGkNB7-OAX4cSiNcjSA',
    lectureData_id: '1pZnWJlW4C3WQsKq4B90gmCL8ORsCf3yj',
    studentData_id: '1ziFcZenGCf_qQDHkjwA7aLyPBde0od0N',
    driveImage_id: '1KaWFZTpECwlanpYovIapqWFIinsnTUVw',
    driveVideo_id: '1qzXI3D0OEnelcgOjbEtHQYJ6KTv0EM92',
    video_marker: true,
    donviquanly: 'Đại Học Thái Nguyên',
    donvitructhuoc: 'Trường Đại Học CNTT & TT',
    class_main: '',
    file_server: 'serverAws',
    title: 'DTKH-ICTU',
    domain: 'dtkh.ictu.edu.vn',
    codeByLvl: true,
    unlimitLesson: false,
    appVersion: '3.0.45',
    newTestThuchanh: true,
    dragDropLesson: false,
    isDttx: false,
    loadNewCom: true,
    no_test_question: false,
}
